# Generated by Django 3.1.1 on 2020-09-23 07:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('f_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_Name', models.CharField(max_length=50, verbose_name='Last name')),
                ('image', models.ImageField(upload_to='Profile/')),
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Student ID')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('current_age', models.CharField(max_length=50, verbose_name='Current age')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, verbose_name='Gender')),
                ('state', django_countries.fields.CountryField(max_length=2)),
                ('city_street', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('telephone_number', models.IntegerField()),
                ('mother_tonque', models.CharField(max_length=70)),
                ('payment_method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
